FROM ubuntu

RUN apt-get update 
RUN apt-get install nginx -y
RUN cd /usr/share/nginx/html/
RUN rm -rf index.html
RUN cd /var/www/html/
RUN rm -rf index.nginx-debian.html

COPY index.html /var/www/html/
COPY index.html /usr/share/nginx/html/
RUN service nginx start
EXPOSE 80

CMD ["nginx","-g","daemon off;"] 


